import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(5, GPIO.OUT )
GPIO.output(5, 1)
GPIO.setup(6, GPIO.OUT )
GPIO.output(6, 1)
GPIO.setup(13, GPIO.OUT )
GPIO.output(13, 1)
GPIO.setup(16, GPIO.OUT )
GPIO.output(16, 1)
GPIO.setup(19, GPIO.OUT )
GPIO.output(19, 1)
GPIO.setup(20, GPIO.OUT )
GPIO.output(20, 1)
GPIO.setup(21, GPIO.OUT )
GPIO.output(21, 1)
GPIO.setup(26, GPIO.OUT )
GPIO.output(26, 1)
